apiVersion: 1

datasources:
  - name: Retail PostgreSQL
    uid: retail-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: retail_user
    secureJsonData:
      password: retail_password
    jsonData:
      database: retail
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
